// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartySchoolApi.Data;

#nullable disable

namespace PartySchoolApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812060113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("content_categories");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentTag", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("ContentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("content_tags");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("question_ids");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("exam_papers");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deadline");

                    b.Property<int>("PaperId")
                        .HasColumnType("int")
                        .HasColumnName("paper_id");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("publisher_id");

                    b.Property<int>("TargetOrgId")
                        .HasColumnType("int")
                        .HasColumnName("target_org_id");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("int")
                        .HasColumnName("time_limit_minutes");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("TargetOrgId");

                    b.ToTable("exam_tests");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("ContentType")
                        .HasColumnType("int")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContentType");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Title");

                    b.ToTable("learning_contents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deadline");

                    b.Property<int>("TargetOrgId")
                        .HasColumnType("int")
                        .HasColumnName("target_org_id");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("task_name");

                    b.HasKey("Id");

                    b.HasIndex("TargetOrgId");

                    b.ToTable("learning_tasks");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberLearningProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_completed");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("MemberId", "ContentId", "TaskId");

                    b.ToTable("member_learning_progress");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberTestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("answers");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TestId");

                    b.HasIndex("MemberId", "TestId");

                    b.ToTable("member_test_records");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("party_members");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("options");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int")
                        .HasColumnName("question_type");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stem");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionType");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.QuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("question_categories");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.TaskContent", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.HasKey("TaskId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("task_contents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentCategory", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.ContentCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentTag", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.LearningContent", "Content")
                        .WithMany("ContentTags")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.Tag", "Tag")
                        .WithMany("ContentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamTest", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.ExamPaper", "Paper")
                        .WithMany("ExamTests")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "TargetOrg")
                        .WithMany()
                        .HasForeignKey("TargetOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("Publisher");

                    b.Navigation("TargetOrg");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningContent", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.ContentCategory", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningTask", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "TargetOrg")
                        .WithMany()
                        .HasForeignKey("TargetOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetOrg");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberLearningProgress", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.LearningContent", "Content")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Member")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.LearningTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Content");

                    b.Navigation("Member");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberTestRecord", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Member")
                        .WithMany("TestRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.ExamTest", "Test")
                        .WithMany("TestRecords")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Organization", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyMember", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Question", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.QuestionCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.TaskContent", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.LearningContent", "Content")
                        .WithMany("TaskContents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.LearningTask", "Task")
                        .WithMany("TaskContents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamPaper", b =>
                {
                    b.Navigation("ExamTests");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamTest", b =>
                {
                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningContent", b =>
                {
                    b.Navigation("ContentTags");

                    b.Navigation("LearningProgresses");

                    b.Navigation("TaskContents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningTask", b =>
                {
                    b.Navigation("TaskContents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Organization", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyMember", b =>
                {
                    b.Navigation("LearningProgresses");

                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.QuestionCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Tag", b =>
                {
                    b.Navigation("ContentTags");
                });
#pragma warning restore 612, 618
        }
    }
}
