// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartySchoolApi.Data;

#nullable disable

namespace PartySchoolApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ActivityHeart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiPolishSuggestion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("MeetingActivityId")
                        .HasColumnType("int");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingActivityId");

                    b.HasIndex("PartyMemberId");

                    b.ToTable("ActivityHearts");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.AntiCheatRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("challenge_id");

                    b.Property<int?>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<bool>("IsPass")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_pass");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int")
                        .HasColumnName("party_member_id");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("PartyMemberId", "VerifiedAt");

                    b.ToTable("anticheat_records");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.BattleGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengerId")
                        .HasColumnType("int")
                        .HasColumnName("challenger_id");

                    b.Property<int>("ChallengerScore")
                        .HasColumnType("int")
                        .HasColumnName("challenger_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("int")
                        .HasColumnName("current_question_index");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<int>("OpponentId")
                        .HasColumnType("int")
                        .HasColumnName("opponent_id");

                    b.Property<int>("OpponentScore")
                        .HasColumnType("int")
                        .HasColumnName("opponent_score");

                    b.Property<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("question_ids");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TimeoutMinutes")
                        .HasColumnType("int")
                        .HasColumnName("timeout_minutes");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerId");

                    b.HasIndex("OpponentId");

                    b.ToTable("battle_games");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.BattleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BattleTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ChallengerId")
                        .HasColumnType("int");

                    b.Property<int>("OpponentId")
                        .HasColumnType("int");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerId");

                    b.HasIndex("OpponentId");

                    b.ToTable("BattleRecords");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.CheckInRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiBackgroundInterpretation")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationName");

                    b.HasIndex("PartyMemberId");

                    b.HasIndex("SiteId");

                    b.ToTable("CheckInRecords");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("content_categories");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentTag", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("ContentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("content_tags");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.EducationSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("AiInterpretation")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("ai_interpretation");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("HistoricalFacts")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("historical_facts");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("education_sites");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("question_ids");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("exam_papers");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAiGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("TargetOrgId")
                        .HasColumnType("int");

                    b.Property<string>("TargetWeaknessTags")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("TargetOrgId");

                    b.ToTable("ExamTests");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RelatedDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SourceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContentType");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Title");

                    b.ToTable("LearningContents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartyMemberId");

                    b.HasIndex("SourceType");

                    b.ToTable("LearningPoints");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deadline");

                    b.Property<int>("TargetOrgId")
                        .HasColumnType("int")
                        .HasColumnName("target_org_id");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("task_name");

                    b.HasKey("Id");

                    b.HasIndex("TargetOrgId");

                    b.ToTable("learning_tasks");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MeetingActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AiSummaryContent")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<bool>("IsAiSummaryGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTime");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Type");

                    b.ToTable("MeetingActivities");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberLearningProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_completed");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("MemberId", "ContentId", "TaskId");

                    b.ToTable("member_learning_progress");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberLearningReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("PartyMemberId");

                    b.ToTable("MemberLearningReports");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberTestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("answers");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TestId");

                    b.HasIndex("MemberId", "TestId");

                    b.ToTable("member_test_records");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MessageNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("PartyMemberId");

                    b.ToTable("MessageNotifications");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Nl2SqlSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("explanation");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("question");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("result_summary");

                    b.Property<string>("Rewritten")
                        .HasColumnType("longtext")
                        .HasColumnName("rewritten");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("SqlText")
                        .HasColumnType("longtext")
                        .HasColumnName("sql_text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("nl2sql_sessions");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.OrgRectification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("issue");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("quarter");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("suggestion");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Quarter");

                    b.ToTable("org_rectifications");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.OrganizationQuarterlyRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("detail_json");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("quarter");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("rating");

                    b.Property<decimal>("RatingScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("rating_score");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Quarter")
                        .IsUnique();

                    b.ToTable("organization_quarterly_ratings");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.OrganizationQuarterlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Quarter");

                    b.ToTable("OrganizationQuarterlyReports");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PairHelpRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HelpContentJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("HelpReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("HelperId")
                        .HasColumnType("int");

                    b.Property<string>("OutcomeSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HelpReceiverId");

                    b.HasIndex("HelperId");

                    b.ToTable("PairHelpRecords");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PairHelpRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("HelpReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("help_receiver_id");

                    b.Property<int>("HelperId")
                        .HasColumnType("int")
                        .HasColumnName("helper_id");

                    b.Property<string>("MatchReason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("match_reason");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HelpReceiverId");

                    b.HasIndex("HelperId");

                    b.ToTable("pair_help_requests");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyDevelopmentProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsReminderSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaterialsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int");

                    b.Property<string>("ReportContent")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PartyMemberId");

                    b.HasIndex("Stage");

                    b.HasIndex("Status");

                    b.ToTable("PartyDevelopmentProcesses");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyDevelopmentReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("PartyMemberId")
                        .HasColumnType("int")
                        .HasColumnName("party_member_id");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reminder_type");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PartyMemberId");

                    b.HasIndex("ProcessId");

                    b.ToTable("party_development_reminders");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PointTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("PartyMembers");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("options");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int")
                        .HasColumnName("question_type");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stem");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionType");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.QuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("question_categories");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.TaskContent", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.HasKey("TaskId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("task_contents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ActivityHeart", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.MeetingActivity", "MeetingActivity")
                        .WithMany("ActivityHearts")
                        .HasForeignKey("MeetingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingActivity");

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.AntiCheatRecord", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.BattleGame", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Challenger")
                        .WithMany()
                        .HasForeignKey("ChallengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenger");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.BattleRecord", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Challenger")
                        .WithMany()
                        .HasForeignKey("ChallengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenger");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.CheckInRecord", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentCategory", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.ContentCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentTag", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.LearningContent", "Content")
                        .WithMany("ContentTags")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.Tag", "Tag")
                        .WithMany("ContentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamTest", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.ExamPaper", "Paper")
                        .WithMany("ExamTests")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "TargetOrg")
                        .WithMany()
                        .HasForeignKey("TargetOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("Publisher");

                    b.Navigation("TargetOrg");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningContent", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.ContentCategory", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningPoint", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningTask", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "TargetOrg")
                        .WithMany()
                        .HasForeignKey("TargetOrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetOrg");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MeetingActivity", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberLearningProgress", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.LearningContent", "Content")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Member")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.LearningTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Content");

                    b.Navigation("Member");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberLearningReport", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MemberTestRecord", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Member")
                        .WithMany("TestRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.ExamTest", "Test")
                        .WithMany("TestRecords")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MessageNotification", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Nl2SqlSession", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.OrgRectification", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Organization", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.OrganizationQuarterlyRating", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.OrganizationQuarterlyReport", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PairHelpRecord", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "HelpReceiver")
                        .WithMany()
                        .HasForeignKey("HelpReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Helper")
                        .WithMany()
                        .HasForeignKey("HelperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HelpReceiver");

                    b.Navigation("Helper");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PairHelpRequest", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "HelpReceiver")
                        .WithMany()
                        .HasForeignKey("HelpReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "Helper")
                        .WithMany()
                        .HasForeignKey("HelperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HelpReceiver");

                    b.Navigation("Helper");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyDevelopmentProcess", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyDevelopmentReminder", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.PartyMember", "PartyMember")
                        .WithMany()
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.PartyDevelopmentProcess", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyMember", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Question", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.QuestionCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.TaskContent", b =>
                {
                    b.HasOne("PartySchoolApi.Models.Entities.LearningContent", "Content")
                        .WithMany("TaskContents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartySchoolApi.Models.Entities.LearningTask", "Task")
                        .WithMany("TaskContents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ContentCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamPaper", b =>
                {
                    b.Navigation("ExamTests");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.ExamTest", b =>
                {
                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningContent", b =>
                {
                    b.Navigation("ContentTags");

                    b.Navigation("LearningProgresses");

                    b.Navigation("TaskContents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.LearningTask", b =>
                {
                    b.Navigation("TaskContents");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.MeetingActivity", b =>
                {
                    b.Navigation("ActivityHearts");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Organization", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.PartyMember", b =>
                {
                    b.Navigation("LearningProgresses");

                    b.Navigation("TestRecords");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.QuestionCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PartySchoolApi.Models.Entities.Tag", b =>
                {
                    b.Navigation("ContentTags");
                });
#pragma warning restore 612, 618
        }
    }
}
